name: test-build-audit
on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - v[0-9]*
  push:
    branches:
      - main
      - v[0-9]*
jobs:
  check-source-code-validity:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Verify content formatting validity (Markdown lint)"
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            README.md
            exampleSite/content/*.md
            exampleSite/content/**/*.md
  audit-only:
    needs: check-source-code-validity
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run build-audit-action-hugo-dfd from src dir to public
        uses: ./
        with:
          base-url: https://example.com/
          source-directory: exampleSite
  create-artifact:
    needs: check-source-code-validity
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run hugo-action-build-audit from src dir to public
        uses: ./
        with:
          source-directory: exampleSite
          upload-site-as: unminified-site
